// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ASPProject.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Navigate - Use 'NavigateParams' to pass parameters into this method.
        /// </summary>
        public void Navigate()
        {
            #region Variable Declarations
            HtmlHyperlink uISklepHyperlink = this.UIMSNPolskaOutlookSkypWindow.UIMSNPolskaOutlookSkypDocument.UIMainCustom.UISklepHyperlink;
            HtmlEdit uIQEdit = this.UIMSNPolskaOutlookSkypWindow.UIMSNPolskaOutlookSkypDocument.UIQEdit;
            BrowserWindow uIMSNPolskaOutlookSkypWindow = this.UIMSNPolskaOutlookSkypWindow;
            #endregion

            // Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=619797&pc=UE13&ocid=UE13DHP' using new browser instance
            this.UIMSNPolskaOutlookSkypWindow.LaunchUrl(new System.Uri(this.NavigateParams.UIMSNPolskaOutlookSkypWindowUrl));

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Go to web page 'http://aspprojekt.azurewebsites.net/'
            uIMSNPolskaOutlookSkypWindow.NavigateToUrl(new System.Uri(this.NavigateParams.UIMSNPolskaOutlookSkypWindowUrl1));
        }
        
        /// <summary>
        /// Login - Use 'LoginParams' to pass parameters into this method.
        /// </summary>
        public void Login()
        {
            #region Variable Declarations
            HtmlHyperlink uIZalogujHyperlink = this.UIStronaGłównaThrowItIWindow.UIStronaGłównaThrowItDocument.UIZalogujHyperlink;
            HtmlEdit uIEmailEdit = this.UIStronaGłównaThrowItIWindow.UIZalogujThrowItDocument.UIEmailEdit;
            HtmlEdit uIHasłoEdit = this.UIStronaGłównaThrowItIWindow.UIZalogujThrowItDocument.UIHasłoEdit;
            HtmlInputButton uIZalogujButton = this.UIStronaGłównaThrowItIWindow.UIZalogujThrowItDocument.UIZalogujButton;
            HtmlDiv uIWitajAdminPane = this.UIStronaGłównaThrowItIWindow.UIStronaGłównaThrowItDocument.UIWitajAdminPane;
            #endregion

            // Click 'Zaloguj' link
            Mouse.Click(uIZalogujHyperlink, new Point(36, 15));

            // Type 'admin@admin.net' in 'Email' text box
            uIEmailEdit.Text = this.LoginParams.UIEmailEditText;

            // Type '********' in 'Hasło' text box
            uIHasłoEdit.Password = this.LoginParams.UIHasłoEditPassword;

            // Click 'Zaloguj' button
            Mouse.Click(uIZalogujButton, new Point(44, 20));

            // Click 'Witaj Admin.' pane
            Mouse.Click(uIWitajAdminPane, new Point(80, 22));
        }
        
        /// <summary>
        /// UserCheck - Use 'UserCheckExpectedValues' to pass parameters into this method.
        /// </summary>
        public void UserCheck()
        {
            #region Variable Declarations
            HtmlDiv uIWitajAdminPane = this.UIStronaGłównaThrowItIWindow.UIStronaGłównaThrowItDocument.UIWitajAdminPane;
            #endregion

            // Verify that the 'InnerText' property of 'Witaj Admin.' pane equals 'Witaj Admin. '
            Assert.AreEqual(this.UserCheckExpectedValues.UIWitajAdminPaneInnerText, uIWitajAdminPane.InnerText);
        }
        
        /// <summary>
        /// CreateBin - Use 'CreateBinParams' to pass parameters into this method.
        /// </summary>
        public void CreateBin()
        {
            #region Variable Declarations
            HtmlHyperlink uINowyśmietnikHyperlink = this.UIStronaGłównaThrowItIWindow.UIStronaGłównaThrowItDocument.UINowyśmietnikHyperlink;
            HtmlEdit uINazwaEdit = this.UIStronaGłównaThrowItIWindow.UINowyThrowItDocument.UINazwaEdit;
            HtmlEdit uIOpisEdit = this.UIStronaGłównaThrowItIWindow.UINowyThrowItDocument.UIOpisEdit;
            HtmlInputButton uIStwórzButton = this.UIStronaGłównaThrowItIWindow.UINowyThrowItDocument.UIStwórzButton;
            HtmlDiv uIAdminBinPane1 = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIAdminBinPane.UIAdminBinPane1;
            #endregion

            // Click 'Nowy śmietnik' link
            Mouse.Click(uINowyśmietnikHyperlink, new Point(75, 27));

            // Type 'Bin' in 'Nazwa' text box
            uINazwaEdit.Text = this.CreateBinParams.UINazwaEditText;

            // Type '{Tab}' in 'Nazwa' text box
            Keyboard.SendKeys(uINazwaEdit, this.CreateBinParams.UINazwaEditSendKeys, ModifierKeys.None);

            // Type 'BinDesc' in 'Opis' text box
            uIOpisEdit.Text = this.CreateBinParams.UIOpisEditText;

            // Click 'Stwórz' button
            Mouse.Click(uIStwórzButton, new Point(44, 29));

            // Click 'Admin : Bin' pane
            Mouse.Click(uIAdminBinPane1, new Point(73, 41));
        }
        
        /// <summary>
        /// CheckName - Use 'CheckNameExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckName()
        {
            #region Variable Declarations
            HtmlDiv uIAdminBinPane1 = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIAdminBinPane.UIAdminBinPane1;
            #endregion

            // Verify that the 'FriendlyName' property of 'Admin : Bin' pane equals 'Admin : Bin'
            Assert.AreEqual(this.CheckNameExpectedValues.UIAdminBinPane1FriendlyName, uIAdminBinPane1.FriendlyName);
        }
        
        /// <summary>
        /// Rename - Use 'RenameParams' to pass parameters into this method.
        /// </summary>
        public void Rename()
        {
            #region Variable Declarations
            HtmlHyperlink uIBinHyperlink = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIBinHyperlink;
            HtmlHyperlink uIEdytujHyperlink = this.UIStronaGłównaThrowItIWindow.UIBinThrowItDocument.UIEdytujHyperlink;
            HtmlEdit uINazwaEdit = this.UIStronaGłównaThrowItIWindow.UIEdycjaThrowItDocument.UINazwaEdit;
            HtmlInputButton uIZapiszButton = this.UIStronaGłównaThrowItIWindow.UIEdycjaThrowItDocument.UIZapiszButton;
            HtmlHyperlink uIBinsHyperlink = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIBinsHyperlink;
            HtmlDiv uIAdminBinsPane = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIAdminBinsPane;
            HtmlDiv uIAdminBinsPane1 = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIAdminBinsPane1.UIAdminBinsPane;
            #endregion

            // Click 'Bin' link
            Mouse.Click(uIBinHyperlink, new Point(23, 15));

            // Click 'Edytuj' link
            Mouse.Click(uIEdytujHyperlink, new Point(28, 20));

            // Type 'Bins' in 'Nazwa' text box
            uINazwaEdit.Text = this.RenameParams.UINazwaEditText;

            // Click 'Zapisz' button
            Mouse.Click(uIZapiszButton, new Point(37, 21));

            // Move 'Bins' link to 'Admin : Bins' pane
            uIAdminBinsPane.EnsureClickable(new Point(235, 139));
            Mouse.StartDragging(uIBinsHyperlink, new Point(33, 14));
            Mouse.StopDragging(uIAdminBinsPane, new Point(235, 139));

            // Click 'Admin : Bins' pane
            Mouse.Click(uIAdminBinsPane1, new Point(135, 34));
        }
        
        /// <summary>
        /// CheckNameAfter - Use 'CheckNameAfterExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckNameAfter()
        {
            #region Variable Declarations
            HtmlDiv uIAdminBinsPane = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIAdminBinsPane1.UIAdminBinsPane;
            #endregion

            // Verify that the 'FriendlyName' property of 'Admin : Bins' pane equals 'Admin : Bins'
            Assert.AreEqual(this.CheckNameAfterExpectedValues.UIAdminBinsPaneFriendlyName, uIAdminBinsPane.FriendlyName);
        }
        
        /// <summary>
        /// Delete
        /// </summary>
        public void Delete()
        {
            #region Variable Declarations
            HtmlHyperlink uIBinsHyperlink = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIBinsHyperlink;
            HtmlHyperlink uIUsuńHyperlink = this.UIStronaGłównaThrowItIWindow.UIBinsThrowItDocument.UIUsuńHyperlink;
            HtmlInputButton uIUsuńButton = this.UIStronaGłównaThrowItIWindow.UIUsuńThrowItDocument.UIUsuńButton;
            HtmlDiv uIBinsContainerPane = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIBinsContainerPane;
            #endregion

            // Click 'Bins' link
            Mouse.Click(uIBinsHyperlink, new Point(28, 18));

            // Click 'Usuń' link
            Mouse.Click(uIUsuńHyperlink, new Point(43, 25));

            // Click 'Usuń' button
            Mouse.Click(uIUsuńButton, new Point(13, 26));

            // Click 'binsContainer' pane
            Mouse.Click(uIBinsContainerPane, new Point(34, 15));
        }
        
        /// <summary>
        /// CheckDelete - Use 'CheckDeleteExpectedValues' to pass parameters into this method.
        /// </summary>
        public void CheckDelete()
        {
            #region Variable Declarations
            HtmlDiv uIBinsContainerPane = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIBinsContainerPane;
            #endregion

            // Verify that the 'InnerText' property of 'binsContainer' pane equals ''
            Assert.AreEqual(this.CheckDeleteExpectedValues.UIBinsContainerPaneInnerText, uIBinsContainerPane.InnerText);
        }
        
        /// <summary>
        /// Logout
        /// </summary>
        public void Logout()
        {
            #region Variable Declarations
            HtmlHyperlink uIWylogujHyperlink = this.UIStronaGłównaThrowItIWindow.UIŚmietnikiThrowItDocument.UIWylogujHyperlink;
            #endregion

            // Click 'Wyloguj' link
            Mouse.Click(uIWylogujHyperlink, new Point(42, 19));
        }
        
        #region Properties
        public virtual NavigateParams NavigateParams
        {
            get
            {
                if ((this.mNavigateParams == null))
                {
                    this.mNavigateParams = new NavigateParams();
                }
                return this.mNavigateParams;
            }
        }
        
        public virtual LoginParams LoginParams
        {
            get
            {
                if ((this.mLoginParams == null))
                {
                    this.mLoginParams = new LoginParams();
                }
                return this.mLoginParams;
            }
        }
        
        public virtual UserCheckExpectedValues UserCheckExpectedValues
        {
            get
            {
                if ((this.mUserCheckExpectedValues == null))
                {
                    this.mUserCheckExpectedValues = new UserCheckExpectedValues();
                }
                return this.mUserCheckExpectedValues;
            }
        }
        
        public virtual CreateBinParams CreateBinParams
        {
            get
            {
                if ((this.mCreateBinParams == null))
                {
                    this.mCreateBinParams = new CreateBinParams();
                }
                return this.mCreateBinParams;
            }
        }
        
        public virtual CheckNameExpectedValues CheckNameExpectedValues
        {
            get
            {
                if ((this.mCheckNameExpectedValues == null))
                {
                    this.mCheckNameExpectedValues = new CheckNameExpectedValues();
                }
                return this.mCheckNameExpectedValues;
            }
        }
        
        public virtual RenameParams RenameParams
        {
            get
            {
                if ((this.mRenameParams == null))
                {
                    this.mRenameParams = new RenameParams();
                }
                return this.mRenameParams;
            }
        }
        
        public virtual CheckNameAfterExpectedValues CheckNameAfterExpectedValues
        {
            get
            {
                if ((this.mCheckNameAfterExpectedValues == null))
                {
                    this.mCheckNameAfterExpectedValues = new CheckNameAfterExpectedValues();
                }
                return this.mCheckNameAfterExpectedValues;
            }
        }
        
        public virtual CheckDeleteExpectedValues CheckDeleteExpectedValues
        {
            get
            {
                if ((this.mCheckDeleteExpectedValues == null))
                {
                    this.mCheckDeleteExpectedValues = new CheckDeleteExpectedValues();
                }
                return this.mCheckDeleteExpectedValues;
            }
        }
        
        public UIMSNPolskaOutlookSkypWindow UIMSNPolskaOutlookSkypWindow
        {
            get
            {
                if ((this.mUIMSNPolskaOutlookSkypWindow == null))
                {
                    this.mUIMSNPolskaOutlookSkypWindow = new UIMSNPolskaOutlookSkypWindow();
                }
                return this.mUIMSNPolskaOutlookSkypWindow;
            }
        }
        
        public UIStronaGłównaThrowItIWindow UIStronaGłównaThrowItIWindow
        {
            get
            {
                if ((this.mUIStronaGłównaThrowItIWindow == null))
                {
                    this.mUIStronaGłównaThrowItIWindow = new UIStronaGłównaThrowItIWindow();
                }
                return this.mUIStronaGłównaThrowItIWindow;
            }
        }
        #endregion
        
        #region Fields
        private NavigateParams mNavigateParams;
        
        private LoginParams mLoginParams;
        
        private UserCheckExpectedValues mUserCheckExpectedValues;
        
        private CreateBinParams mCreateBinParams;
        
        private CheckNameExpectedValues mCheckNameExpectedValues;
        
        private RenameParams mRenameParams;
        
        private CheckNameAfterExpectedValues mCheckNameAfterExpectedValues;
        
        private CheckDeleteExpectedValues mCheckDeleteExpectedValues;
        
        private UIMSNPolskaOutlookSkypWindow mUIMSNPolskaOutlookSkypWindow;
        
        private UIStronaGłównaThrowItIWindow mUIStronaGłównaThrowItIWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Navigate'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class NavigateParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://go.microsoft.com/fwlink/p/?LinkId=619797&pc=UE13&ocid=UE13DHP' using new browser instance
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl = "http://go.microsoft.com/fwlink/p/?LinkId=619797&pc=UE13&ocid=UE13DHP";
        
        /// <summary>
        /// Go to web page 'http://aspprojekt.azurewebsites.net/'
        /// </summary>
        public string UIMSNPolskaOutlookSkypWindowUrl1 = "http://aspprojekt.azurewebsites.net/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin@admin.net' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "admin@admin.net";
        
        /// <summary>
        /// Type '********' in 'Hasło' text box
        /// </summary>
        public string UIHasłoEditPassword = "IidrX+WPyaS3vRV6qxlDlKoP95Rhhzue";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'UserCheck'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UserCheckExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Witaj Admin.' pane equals 'Witaj Admin. '
        /// </summary>
        public string UIWitajAdminPaneInnerText = "Witaj Admin. ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateBin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CreateBinParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Bin' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "Bin";
        
        /// <summary>
        /// Type '{Tab}' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'BinDesc' in 'Opis' text box
        /// </summary>
        public string UIOpisEditText = "BinDesc";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckName'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckNameExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'FriendlyName' property of 'Admin : Bin' pane equals 'Admin : Bin'
        /// </summary>
        public string UIAdminBinPane1FriendlyName = "Admin : Bin";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Rename'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RenameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Bins' in 'Nazwa' text box
        /// </summary>
        public string UINazwaEditText = "Bins";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckNameAfter'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckNameAfterExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'FriendlyName' property of 'Admin : Bins' pane equals 'Admin : Bins'
        /// </summary>
        public string UIAdminBinsPaneFriendlyName = "Admin : Bins";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CheckDelete'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class CheckDeleteExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'binsContainer' pane equals ''
        /// </summary>
        public string UIBinsContainerPaneInnerText = null;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNPolskaOutlookSkypWindow : BrowserWindow
    {
        
        public UIMSNPolskaOutlookSkypWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                "ve";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                    "ve");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIMSNPolskaOutlookSkypDocument UIMSNPolskaOutlookSkypDocument
        {
            get
            {
                if ((this.mUIMSNPolskaOutlookSkypDocument == null))
                {
                    this.mUIMSNPolskaOutlookSkypDocument = new UIMSNPolskaOutlookSkypDocument(this);
                }
                return this.mUIMSNPolskaOutlookSkypDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIMSNPolskaOutlookSkypDocument mUIMSNPolskaOutlookSkypDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMSNPolskaOutlookSkypDocument : HtmlDocument
    {
        
        public UIMSNPolskaOutlookSkypDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                "ve";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/pl-pl/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.msn.com/pl-pl/?pc=EUPP_UE13&ocid=UE13DHP";
            this.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                    "ve");
            #endregion
        }
        
        #region Properties
        public UIMainCustom UIMainCustom
        {
            get
            {
                if ((this.mUIMainCustom == null))
                {
                    this.mUIMainCustom = new UIMainCustom(this);
                }
                return this.mUIMainCustom;
            }
        }
        
        public HtmlEdit UIQEdit
        {
            get
            {
                if ((this.mUIQEdit == null))
                {
                    this.mUIQEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "q";
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" id=\"q\" accesskey=\"S\" aria-label";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIQEdit.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                            "ve");
                    #endregion
                }
                return this.mUIQEdit;
            }
        }
        #endregion
        
        #region Fields
        private UIMainCustom mUIMainCustom;
        
        private HtmlEdit mUIQEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainCustom : HtmlCustom
    {
        
        public UIMainCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "main";
            this.SearchProperties["Id"] = "main";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"main\" role=\"main\" data-m=\'{\"i\":17,\"n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                    "ve");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISklepHyperlink
        {
            get
            {
                if ((this.mUISklepHyperlink == null))
                {
                    this.mUISklepHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISklepHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISklepHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISklepHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUISklepHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sklep";
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/click";
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://clk.tradedoubler.com/click?p=270365&a=2811327&g=0&epi=Prime_PLPL_HP_MEStor" +
                        "eL1&url=https://www.microsoftstore.com/store/mseea1/pl_PL/home?icid=MSN_storeTIL" +
                        "E";
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"http://clk.tradedoubler.com/click?";
                    this.mUISklepHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUISklepHyperlink.WindowTitles.Add("MSN Polska - Outlook, Skype, Hotmail, Messenger, Microsoft Office Online i OneDri" +
                            "ve");
                    #endregion
                }
                return this.mUISklepHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISklepHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStronaGłównaThrowItIWindow : BrowserWindow
    {
        
        public UIStronaGłównaThrowItIWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Strona Główna - ThrowIt";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Strona Główna - ThrowIt");
            this.WindowTitles.Add("Zaloguj - ThrowIt");
            this.WindowTitles.Add("Nowy - ThrowIt");
            this.WindowTitles.Add("Śmietniki - ThrowIt");
            this.WindowTitles.Add("Bin - ThrowIt");
            this.WindowTitles.Add("Edycja - ThrowIt");
            this.WindowTitles.Add("Bins - ThrowIt");
            this.WindowTitles.Add("Usuń - ThrowIt");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIStronaGłównaThrowItDocument UIStronaGłównaThrowItDocument
        {
            get
            {
                if ((this.mUIStronaGłównaThrowItDocument == null))
                {
                    this.mUIStronaGłównaThrowItDocument = new UIStronaGłównaThrowItDocument(this);
                }
                return this.mUIStronaGłównaThrowItDocument;
            }
        }
        
        public UIZalogujThrowItDocument UIZalogujThrowItDocument
        {
            get
            {
                if ((this.mUIZalogujThrowItDocument == null))
                {
                    this.mUIZalogujThrowItDocument = new UIZalogujThrowItDocument(this);
                }
                return this.mUIZalogujThrowItDocument;
            }
        }
        
        public UINowyThrowItDocument UINowyThrowItDocument
        {
            get
            {
                if ((this.mUINowyThrowItDocument == null))
                {
                    this.mUINowyThrowItDocument = new UINowyThrowItDocument(this);
                }
                return this.mUINowyThrowItDocument;
            }
        }
        
        public UIŚmietnikiThrowItDocument UIŚmietnikiThrowItDocument
        {
            get
            {
                if ((this.mUIŚmietnikiThrowItDocument == null))
                {
                    this.mUIŚmietnikiThrowItDocument = new UIŚmietnikiThrowItDocument(this);
                }
                return this.mUIŚmietnikiThrowItDocument;
            }
        }
        
        public UIBinThrowItDocument UIBinThrowItDocument
        {
            get
            {
                if ((this.mUIBinThrowItDocument == null))
                {
                    this.mUIBinThrowItDocument = new UIBinThrowItDocument(this);
                }
                return this.mUIBinThrowItDocument;
            }
        }
        
        public UIEdycjaThrowItDocument UIEdycjaThrowItDocument
        {
            get
            {
                if ((this.mUIEdycjaThrowItDocument == null))
                {
                    this.mUIEdycjaThrowItDocument = new UIEdycjaThrowItDocument(this);
                }
                return this.mUIEdycjaThrowItDocument;
            }
        }
        
        public UIBinsThrowItDocument UIBinsThrowItDocument
        {
            get
            {
                if ((this.mUIBinsThrowItDocument == null))
                {
                    this.mUIBinsThrowItDocument = new UIBinsThrowItDocument(this);
                }
                return this.mUIBinsThrowItDocument;
            }
        }
        
        public UIUsuńThrowItDocument UIUsuńThrowItDocument
        {
            get
            {
                if ((this.mUIUsuńThrowItDocument == null))
                {
                    this.mUIUsuńThrowItDocument = new UIUsuńThrowItDocument(this);
                }
                return this.mUIUsuńThrowItDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIStronaGłównaThrowItDocument mUIStronaGłównaThrowItDocument;
        
        private UIZalogujThrowItDocument mUIZalogujThrowItDocument;
        
        private UINowyThrowItDocument mUINowyThrowItDocument;
        
        private UIŚmietnikiThrowItDocument mUIŚmietnikiThrowItDocument;
        
        private UIBinThrowItDocument mUIBinThrowItDocument;
        
        private UIEdycjaThrowItDocument mUIEdycjaThrowItDocument;
        
        private UIBinsThrowItDocument mUIBinsThrowItDocument;
        
        private UIUsuńThrowItDocument mUIUsuńThrowItDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIStronaGłównaThrowItDocument : HtmlDocument
    {
        
        public UIStronaGłównaThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Strona Główna - ThrowIt";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://aspprojekt.azurewebsites.net/";
            this.WindowTitles.Add("Strona Główna - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIZalogujHyperlink
        {
            get
            {
                if ((this.mUIZalogujHyperlink == null))
                {
                    this.mUIZalogujHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIZalogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "loginLink";
                    this.mUIZalogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIZalogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIZalogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Zaloguj";
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://aspprojekt.azurewebsites.net/Account/Login";
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"loginLink\" href=\"/Account/Login\"";
                    this.mUIZalogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIZalogujHyperlink.WindowTitles.Add("Strona Główna - ThrowIt");
                    #endregion
                }
                return this.mUIZalogujHyperlink;
            }
        }
        
        public HtmlDiv UIWitajAdminPane
        {
            get
            {
                if ((this.mUIWitajAdminPane == null))
                {
                    this.mUIWitajAdminPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWitajAdminPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWitajAdminPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWitajAdminPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Witaj Admin. ";
                    this.mUIWitajAdminPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWitajAdminPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-heading";
                    this.mUIWitajAdminPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-heading\"";
                    this.mUIWitajAdminPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
                    this.mUIWitajAdminPane.WindowTitles.Add("Strona Główna - ThrowIt");
                    #endregion
                }
                return this.mUIWitajAdminPane;
            }
        }
        
        public HtmlHyperlink UINowyśmietnikHyperlink
        {
            get
            {
                if ((this.mUINowyśmietnikHyperlink == null))
                {
                    this.mUINowyśmietnikHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUINowyśmietnikHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUINowyśmietnikHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUINowyśmietnikHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUINowyśmietnikHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Nowy śmietnik";
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Bins/Create";
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://aspprojekt.azurewebsites.net/Bins/Create";
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Bins/Create\"";
                    this.mUINowyśmietnikHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUINowyśmietnikHyperlink.WindowTitles.Add("Strona Główna - ThrowIt");
                    #endregion
                }
                return this.mUINowyśmietnikHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIZalogujHyperlink;
        
        private HtmlDiv mUIWitajAdminPane;
        
        private HtmlHyperlink mUINowyśmietnikHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIZalogujThrowItDocument : HtmlDocument
    {
        
        public UIZalogujThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Zaloguj - ThrowIt";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://aspprojekt.azurewebsites.net/Account/Login";
            this.WindowTitles.Add("Zaloguj - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control\" id=\"em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIEmailEdit.WindowTitles.Add("Zaloguj - ThrowIt");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIHasłoEdit
        {
            get
            {
                if ((this.mUIHasłoEdit == null))
                {
                    this.mUIHasłoEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIHasłoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password";
                    this.mUIHasłoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Hasło";
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIHasłoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIHasłoEdit.WindowTitles.Add("Zaloguj - ThrowIt");
                    #endregion
                }
                return this.mUIHasłoEdit;
            }
        }
        
        public HtmlInputButton UIZalogujButton
        {
            get
            {
                if ((this.mUIZalogujButton == null))
                {
                    this.mUIZalogujButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIZalogujButton.SearchProperties[HtmlButton.PropertyNames.Id] = "loginbutton";
                    this.mUIZalogujButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIZalogujButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Zaloguj";
                    this.mUIZalogujButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIZalogujButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIZalogujButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIZalogujButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"loginbutton\"";
                    this.mUIZalogujButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUIZalogujButton.WindowTitles.Add("Zaloguj - ThrowIt");
                    #endregion
                }
                return this.mUIZalogujButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIHasłoEdit;
        
        private HtmlInputButton mUIZalogujButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINowyThrowItDocument : HtmlDocument
    {
        
        public UINowyThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Nowy - ThrowIt";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Bins/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://aspprojekt.azurewebsites.net/Bins/Create";
            this.WindowTitles.Add("Nowy - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINazwaEdit
        {
            get
            {
                if ((this.mUINazwaEdit == null))
                {
                    this.mUINazwaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "name";
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Name";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwa";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Name\" class=\"form-control text-box";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUINazwaEdit.WindowTitles.Add("Nowy - ThrowIt");
                    #endregion
                }
                return this.mUINazwaEdit;
            }
        }
        
        public HtmlEdit UIOpisEdit
        {
            get
            {
                if ((this.mUIOpisEdit == null))
                {
                    this.mUIOpisEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIOpisEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Description";
                    this.mUIOpisEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Description";
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Opis";
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Description\" class=\"form-control t";
                    this.mUIOpisEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIOpisEdit.WindowTitles.Add("Nowy - ThrowIt");
                    #endregion
                }
                return this.mUIOpisEdit;
            }
        }
        
        public HtmlInputButton UIStwórzButton
        {
            get
            {
                if ((this.mUIStwórzButton == null))
                {
                    this.mUIStwórzButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Id] = "submitBin";
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Stwórz";
                    this.mUIStwórzButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"submitBin\" t";
                    this.mUIStwórzButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUIStwórzButton.WindowTitles.Add("Nowy - ThrowIt");
                    #endregion
                }
                return this.mUIStwórzButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINazwaEdit;
        
        private HtmlEdit mUIOpisEdit;
        
        private HtmlInputButton mUIStwórzButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIŚmietnikiThrowItDocument : HtmlDocument
    {
        
        public UIŚmietnikiThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Śmietniki - ThrowIt";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/User/Admin";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://aspprojekt.azurewebsites.net/User/Admin";
            this.WindowTitles.Add("Śmietniki - ThrowIt");
            #endregion
        }
        
        #region Properties
        public UIAdminBinPane UIAdminBinPane
        {
            get
            {
                if ((this.mUIAdminBinPane == null))
                {
                    this.mUIAdminBinPane = new UIAdminBinPane(this);
                }
                return this.mUIAdminBinPane;
            }
        }
        
        public HtmlHyperlink UIBinHyperlink
        {
            get
            {
                if ((this.mUIBinHyperlink == null))
                {
                    this.mUIBinHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBinHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Bin";
                    this.mUIBinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBinHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "link";
                    this.mUIBinHyperlink.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIBinHyperlink;
            }
        }
        
        public HtmlHyperlink UIBinsHyperlink
        {
            get
            {
                if ((this.mUIBinsHyperlink == null))
                {
                    this.mUIBinsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBinsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBinsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBinsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Bins";
                    this.mUIBinsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBinsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "link";
                    this.mUIBinsHyperlink.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIBinsHyperlink;
            }
        }
        
        public HtmlDiv UIAdminBinsPane
        {
            get
            {
                if ((this.mUIAdminBinsPane == null))
                {
                    this.mUIAdminBinsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAdminBinsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAdminBinsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Admin : Bins ";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\"";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "12";
                    this.mUIAdminBinsPane.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIAdminBinsPane;
            }
        }
        
        public UIAdminBinsPane1 UIAdminBinsPane1
        {
            get
            {
                if ((this.mUIAdminBinsPane1 == null))
                {
                    this.mUIAdminBinsPane1 = new UIAdminBinsPane1(this);
                }
                return this.mUIAdminBinsPane1;
            }
        }
        
        public HtmlDiv UIBinsContainerPane
        {
            get
            {
                if ((this.mUIBinsContainerPane == null))
                {
                    this.mUIBinsContainerPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIBinsContainerPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "binsContainer";
                    this.mUIBinsContainerPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIBinsContainerPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIBinsContainerPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIBinsContainerPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
                    this.mUIBinsContainerPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\" id=\"binsContainer\"";
                    this.mUIBinsContainerPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIBinsContainerPane.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIBinsContainerPane;
            }
        }
        
        public HtmlHyperlink UIWylogujHyperlink
        {
            get
            {
                if ((this.mUIWylogujHyperlink == null))
                {
                    this.mUIWylogujHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWylogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "logout";
                    this.mUIWylogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWylogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWylogujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Wyloguj";
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "document.getElementById(\'logoutForm\').submit()";
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:document.getElementById(\'logoutForm\').submit()";
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"logout\" href=\"javascript:document.ge";
                    this.mUIWylogujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIWylogujHyperlink.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIWylogujHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIAdminBinPane mUIAdminBinPane;
        
        private HtmlHyperlink mUIBinHyperlink;
        
        private HtmlHyperlink mUIBinsHyperlink;
        
        private HtmlDiv mUIAdminBinsPane;
        
        private UIAdminBinsPane1 mUIAdminBinsPane1;
        
        private HtmlDiv mUIBinsContainerPane;
        
        private HtmlHyperlink mUIWylogujHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdminBinPane : HtmlDiv
    {
        
        public UIAdminBinPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "binsContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Admin : Bin ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\" id=\"binsContainer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Śmietniki - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAdminBinPane1
        {
            get
            {
                if ((this.mUIAdminBinPane1 == null))
                {
                    this.mUIAdminBinPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAdminBinPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAdminBinPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAdminBinPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Admin : Bin ";
                    this.mUIAdminBinPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAdminBinPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
                    this.mUIAdminBinPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\"";
                    this.mUIAdminBinPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "16";
                    this.mUIAdminBinPane1.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIAdminBinPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAdminBinPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAdminBinsPane1 : HtmlDiv
    {
        
        public UIAdminBinsPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "binsContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Admin : Bins ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\" id=\"binsContainer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Śmietniki - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIAdminBinsPane
        {
            get
            {
                if ((this.mUIAdminBinsPane == null))
                {
                    this.mUIAdminBinsPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAdminBinsPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAdminBinsPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Admin : Bins ";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "panel-body";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"panel-body\"";
                    this.mUIAdminBinsPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "16";
                    this.mUIAdminBinsPane.WindowTitles.Add("Śmietniki - ThrowIt");
                    #endregion
                }
                return this.mUIAdminBinsPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIAdminBinsPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBinThrowItDocument : HtmlDocument
    {
        
        public UIBinThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Bin - ThrowIt";
            this.WindowTitles.Add("Bin - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIEdytujHyperlink
        {
            get
            {
                if ((this.mUIEdytujHyperlink == null))
                {
                    this.mUIEdytujHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEdytujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEdytujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEdytujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEdytujHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Edytuj";
                    this.mUIEdytujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEdytujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-primary";
                    this.mUIEdytujHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" href=\"/Bins/Edit";
                    this.mUIEdytujHyperlink.WindowTitles.Add("Bin - ThrowIt");
                    #endregion
                }
                return this.mUIEdytujHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIEdytujHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIEdycjaThrowItDocument : HtmlDocument
    {
        
        public UIEdycjaThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Edycja - ThrowIt";
            this.WindowTitles.Add("Edycja - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINazwaEdit
        {
            get
            {
                if ((this.mUINazwaEdit == null))
                {
                    this.mUINazwaEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Name";
                    this.mUINazwaEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Name";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nazwa";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Name\" class=\"form-control text-box";
                    this.mUINazwaEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUINazwaEdit.WindowTitles.Add("Edycja - ThrowIt");
                    #endregion
                }
                return this.mUINazwaEdit;
            }
        }
        
        public HtmlInputButton UIZapiszButton
        {
            get
            {
                if ((this.mUIZapiszButton == null))
                {
                    this.mUIZapiszButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Id] = "submit";
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Zapisz";
                    this.mUIZapiszButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"submit\" type";
                    this.mUIZapiszButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUIZapiszButton.WindowTitles.Add("Edycja - ThrowIt");
                    #endregion
                }
                return this.mUIZapiszButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINazwaEdit;
        
        private HtmlInputButton mUIZapiszButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIBinsThrowItDocument : HtmlDocument
    {
        
        public UIBinsThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Bins - ThrowIt";
            this.WindowTitles.Add("Bins - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIUsuńHyperlink
        {
            get
            {
                if ((this.mUIUsuńHyperlink == null))
                {
                    this.mUIUsuńHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIUsuńHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIUsuńHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIUsuńHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIUsuńHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Usuń";
                    this.mUIUsuńHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIUsuńHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "btn btn-danger";
                    this.mUIUsuńHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"btn btn-danger\" href=\"/Bins/Delet";
                    this.mUIUsuńHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUIUsuńHyperlink.WindowTitles.Add("Bins - ThrowIt");
                    #endregion
                }
                return this.mUIUsuńHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIUsuńHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUsuńThrowItDocument : HtmlDocument
    {
        
        public UIUsuńThrowItDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Usuń - ThrowIt";
            this.WindowTitles.Add("Usuń - ThrowIt");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIUsuńButton
        {
            get
            {
                if ((this.mUIUsuńButton == null))
                {
                    this.mUIUsuńButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIUsuńButton.SearchProperties[HtmlButton.PropertyNames.Id] = "submit";
                    this.mUIUsuńButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIUsuńButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Usuń";
                    this.mUIUsuńButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIUsuńButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIUsuńButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIUsuńButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" id=\"submit\" type";
                    this.mUIUsuńButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIUsuńButton.WindowTitles.Add("Usuń - ThrowIt");
                    #endregion
                }
                return this.mUIUsuńButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIUsuńButton;
        #endregion
    }
}
